name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      CGO_CFLAGS_ALLOW: -Xpreprocessor
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get -y install libopenjp2-7
          sudo apt-get -y install libvips-dev

      - name: Install macos deps
        if: matrix.os == 'macos-latest'
        run: |
          brew install vips

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v ./vips

      - name: Test
        run: go test -v -coverprofile=profile.cov ./...

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest'
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
